const fs = require('node:fs');
const crypto = require('node:crypto');
const esbuild = require('esbuild');

// No lowering of the existing runtime primitives: only collapse the module
// graph into one classic script for legacy Application Cache loading.
esbuild.buildSync({
  entryPoints: ['js/loader-entry.js'],
  bundle: true,
  format: 'iife',
  treeShaking: false,
  target: 'esnext',
  outfile: 'js/loader.js',
  legalComments: 'none',
  banner: { js: '// Generated by npm run build; edit the source modules instead.\n"use strict";' }
});

// Any deployed resource change must invalidate the application cache.
const manifestPath = 'cache.appcache';
const manifest = fs.readFileSync(manifestPath, 'utf8');
const hash = crypto.createHash('sha256');
let section = 'CACHE';
for (const line of manifest.split(/\r?\n/)) {
  const path = line.trim();
  if (!path || path.startsWith('#') || path === 'CACHE MANIFEST') continue;
  if (path.endsWith(':')) { section = path.slice(0, -1); continue; }
  if (section !== 'CACHE') continue;
  hash.update(path);
  hash.update(fs.readFileSync(path.split('?')[0] === './' ? 'index.html' : path.split('?')[0]));
}
fs.writeFileSync(manifestPath, manifest.replace(/^# rev .*$/m, '# rev ' + hash.digest('hex').slice(0, 20)));
